# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/templates/heros.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Enter_Hero(object):
    def setupUi(self, Enter_Hero):
        Enter_Hero.setObjectName("Enter heroes")
        Enter_Hero.resize(299, 142)
        self.centralwidget = QtWidgets.QWidget(Enter_Hero)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(26, 20, 241, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 50, 241, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 90, 89, 25))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        Enter_Hero.setCentralWidget(self.centralwidget)

        self.retranslateUi(Enter_Hero)
        QtCore.QMetaObject.connectSlotsByName(Enter_Hero)

    def retranslateUi(self, Enter_Hero):
        _translate = QtCore.QCoreApplication.translate
        Enter_Hero.setWindowTitle(_translate("Enter_Hero", "Enter Heroes"))
        self.label.setText(_translate("Enter_Hero", "Enter all heros for the player"))
        self.pushButton.setText(_translate("Enter_Hero", "OK"))

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Enter_Hero = QtWidgets.QMainWindow()
#     ui = Ui_Enter_Hero()
#     ui.setupUi(Enter_Hero)
#     Enter_Hero.show()
#     sys.exit(app.exec())
